-- Seed data for books
INSERT INTO public.books (title, author, why, persona_id, module_index, order_index)
VALUES 
('The Fish That Ate the Whale', 'Rich Cohen', 'He toppled governments just to sell bananas. You think you have limits? You don''t. Pure hustle.', 'strategist', 0, 0),
('Titan', 'Ron Chernow', 'Patience. Compounding. Monopoly. He built a machine, not just a company. Study the machine.', 'strategist', 0, 1),
('The House of Morgan', 'Ron Chernow', 'The modern world was built by this family. You need to know how the plumbing of finance works.', 'strategist', 0, 2),
('The Snowball', 'Alice Schroeder', 'He bets on truth. He ignores the noise. Be rational when everyone else is crazy.', 'strategist', 0, 3),
('The Ride of a Lifetime', 'Bob Iger', 'Ego kills companies. He put his ego aside and bought Pixar, Marvel, Star Wars. That is strength.', 'strategist', 0, 4),
('King of Oil', 'Daniel Ammann', 'The world runs on oil. These guys controlled the flow. Understand the supply chain, understand the world.', 'strategist', 0, 5),
('Personal History', 'Katharine Graham', 'She was terrified, but she led anyway. Leadership isn''t about not being scared. It''s about acting.', 'strategist', 0, 6),
('Pour Your Heart Into It', 'Howard Schultz', 'He built a giant with a soul. That is incredibly hard. Scale usually kills culture. Don''t let it.', 'strategist', 0, 7),
('Grinding It Out', 'Ray Kroc', 'He wasn''t a genius. He just worked harder than everyone else. Persistence is the only magic.', 'strategist', 0, 8),
('Sam Walton: Made in America', 'Sam Walton', 'He stayed cheap. He listened to the customer. He ignored Wall Street. Humility wins.', 'strategist', 0, 9),
('Losing the Signal', 'Jacquie McNish', 'They had it all. They got comfortable. They died. Never, ever get comfortable.', 'strategist', 0, 10),
('Hatching Twitter', 'Nick Bilton', 'It looked like a rocket ship. Inside, it was a clown car. Reality is messy. Embrace the mess.', 'strategist', 0, 11),
('The Power Broker', 'Robert Caro', 'You want to build big things? You need to understand power. This is the bible of getting it done.', 'strategist', 1, 0),
('Master of the Senate', 'Robert Caro', 'He turned a boring room into a weapon. It''s about leverage. Find the leverage.', 'strategist', 1, 1),
('Napoleon: A Life', 'Andrew Roberts', 'Ambition. Pure, unfiltered ambition. See how far a single human will can actually go.', 'strategist', 1, 2),
('Grant', 'Ron Chernow', 'He was a failure. Then he saved the Union. Life is long. You can always come back.', 'strategist', 1, 3),
('Team of Rivals', 'Doris Kearns Goodwin', 'Don''t hire friends. Hire people better than you. Even if they hate you. That''s how you win.', 'strategist', 1, 4),
('Leonardo da Vinci', 'Walter Isaacson', 'Art and science are the same thing. Be curious about everything. Everything connects.', 'strategist', 1, 5),
('Kissinger', 'Walter Isaacson', 'The world is messy. Sometimes you have to make hard choices to keep the peace. Grow up and see it.', 'strategist', 1, 6),
('The Wise Men', 'Isaacson & Thomas', 'A few friends designed the post-war world. Never underestimate a small group of smart people.', 'strategist', 1, 7),
('Lee Kuan Yew', 'Memoirs', 'He took a swamp and made it a spaceship. He didn''t make excuses. He built.', 'strategist', 1, 8),
('Churchill: Walking with Destiny', 'Andrew Roberts', 'Words are weapons. When all was lost, he used the English language to save civilization.', 'strategist', 1, 9),
('Caesar: Life of a Colossus', 'Adrian Goldsworthy', 'He crossed the line when nobody else dared. But watch out—ambition has a price.', 'strategist', 1, 10),
('Alexander Hamilton', 'Ron Chernow', 'He built the financial system from scratch. He wrote his way out of poverty. Write your future.', 'strategist', 1, 11),
('Empire of Pain', 'Patrick Radden Keefe', 'They built a dynasty on pain. It shows you what happens when profit eats ethics. Don''t be them.', 'strategist', 2, 0),
('Say Nothing', 'Patrick Radden Keefe', 'History isn''t just dates. It''s people, trauma, and memory. Understand the human cost.', 'strategist', 2, 1),
('The Rogues', 'Patrick Radden Keefe', 'Rebels and grifters. It''s fun, but it teaches you to spot the fakes.', 'strategist', 2, 2),
('Barbarians at the Gate', 'Bryan Burrough', 'Greed. Ego. The 80s. It''s a masterclass in what happens when money becomes the only goal.', 'strategist', 2, 3),
('Liar''s Poker', 'Michael Lewis', 'Wall Street isn''t smarter than you. It''s just louder. See through the noise.', 'strategist', 2, 4),
('The Big Short', 'Michael Lewis', 'The whole world was wrong. A few guys were right. Be the one who actually looks at the data.', 'strategist', 2, 5),
('The Wager', 'David Grann', 'When the ship sinks, who are you? Civilization is thin. Character is everything.', 'strategist', 2, 6),
('Killers of the Flower Moon', 'David Grann', 'Evil exists. It hides in plain sight. Open your eyes.', 'strategist', 2, 7),
('Red Notice', 'Bill Browder', 'You think business is just spreadsheets? Sometimes it''s life or death. Be brave.', 'strategist', 2, 8),
('Freezing Order', 'Bill Browder', 'They tried to stop him. He kept going. Follow the money, find the truth.', 'strategist', 2, 9),
('The Smartest Guys in the Room', 'Bethany McLean', 'They thought they were the smartest guys in the room. They were just arrogant. Don''t be arrogant.', 'strategist', 2, 10),
('Too Big to Fail', 'Andrew Ross Sorkin', 'The system almost collapsed. Understand how fragile the machine actually is.', 'strategist', 2, 11),
('Finite and Infinite Games', 'James Carse', 'Are you playing to win, or playing to keep playing? Build a company for the infinite game.', 'strategist', 3, 0),
('Thinking in Bets', 'Annie Duke', 'Life is poker, not chess. You don''t have all the info. Make the best bet and move on.', 'strategist', 3, 1),
('Superforecasting', 'Philip Tetlock', 'Experts are guessing. You can do better. Learn to update your beliefs when facts change.', 'strategist', 3, 2),
('The Outsiders', 'William Thorndike', 'CEOs love press. These guys loved cash flow. Focus on the result, not the fame.', 'strategist', 3, 3),
('7 Powers', 'Hamilton Helmer', 'If you don''t have a moat, you don''t have a business. Memorize these seven advantages.', 'strategist', 3, 4),
('Competition Demystified', 'Bruce Greenwald', 'Business is war. If it''s easy to enter your market, you''re dead. Build walls.', 'strategist', 3, 5),
('Good Strategy Bad Strategy', 'Richard Rumelt', 'Most strategy is just fluff. Real strategy is solving the hardest problem. Do that.', 'strategist', 3, 6),
('The Black Swan', 'Nassim Nicholas Taleb', 'The thing that kills you is the thing you never saw coming. Survive the impossible.', 'strategist', 3, 7),
('Fooled by Randomness', 'Nassim Nicholas Taleb', 'You got lucky. Don''t confuse it with being smart. Stay humble.', 'strategist', 3, 8),
('Skin in the Game', 'Nassim Nicholas Taleb', 'Never trust a person who doesn''t lose when they''re wrong. Risk is the only truth.', 'strategist', 3, 9),
('Antifragile', 'Nassim Nicholas Taleb', 'Don''t just survive stress. Get stronger from it. Be the thing that loves the chaos.', 'strategist', 3, 10),
('The Bed of Procrustes', 'Nassim Nicholas Taleb', 'Modern life tries to fit you into a box. Break the box.', 'strategist', 3, 11),
('Endurance', 'Alfred Lansing', 'They were stuck in hell on ice. They didn''t quit. If they can survive that, you can survive this.', 'strategist', 4, 0),
('Into Thin Air', 'Jon Krakauer', 'They kept climbing because they spent the money. Sunk cost kills. Know when to turn back.', 'strategist', 4, 1),
('Touching the Void', 'Joe Simpson', 'He was left for dead. He crawled home. The human spirit is unbreakable. Believe it.', 'strategist', 4, 2),
('Man''s Search for Meaning', 'Viktor Frankl', 'You can lose everything but your mind. Find a purpose, and you can survive anything.', 'strategist', 4, 3),
('Unbroken', 'Laura Hillenbrand', 'Pain is temporary. Quitting lasts forever. This guy just refused to break.', 'strategist', 4, 4),
('The Splendid and the Vile', 'Erik Larson', 'Bombs were falling every night. He kept working. Keep working.', 'strategist', 4, 5),
('Dead Wake', 'Erik Larson', 'Technology fails. Arrogance sinks ships. Respect the ocean. Respect the risk.', 'strategist', 4, 6),
('Midnight in Chernobyl', 'Adam Higginbotham', 'Lies destroy systems. When you hide the truth, it explodes. Tell the truth.', 'strategist', 4, 7),
('Alive', 'Piers Paul Read', 'They did the unthinkable to survive. Life wants to live. It''s powerful.', 'strategist', 4, 8),
('Skeletons on the Zahara', 'Dean King', 'The desert doesn''t care about you. Resilience is your only weapon.', 'strategist', 4, 9),
('River of Doubt', 'Candice Millard', 'A President almost died in a jungle. Adventure is dangerous. Do it anyway.', 'strategist', 4, 10),
('Destiny of the Republic', 'Candice Millard', 'Doctors killed him because they wouldn''t wash their hands. Question the experts.', 'strategist', 4, 11),
('The Hard Thing About Hard Things', 'Ben Horowitz', 'School is over. This is the real world. This tells you what to do when everything is burning.', 'founder', 0, 0),
('High Output Management', 'Andrew Grove', 'Output. Leverage. Throughput. This is the physics of management. Study it.', 'founder', 0, 1),
('Only the Paranoid Survive', 'Andrew Grove', 'Success breeds complacency. Only the paranoid survive. Always be looking for the cliff.', 'founder', 0, 2),
('The Effective Executive', 'Peter Drucker', 'Stop being busy. Start being effective. There is a huge difference. Focus on the output.', 'founder', 0, 3),
('Measure What Matters', 'John Doerr', 'If you can''t measure it, it doesn''t exist. Get everyone moving the same way.', 'founder', 0, 4),
('Working Backwards', 'Colin Bryar', 'Amazon doesn''t use PowerPoint. They write memos. Clear writing is clear thinking. Think clearly.', 'founder', 0, 5),
('No Rules Rules', 'Reed Hastings', 'Talent density. Get the best people, pay them top of market, and get out of their way.', 'founder', 0, 6),
('Amp It Up', 'Frank Slootman', 'Move faster. Raise the standards. Most people accept mediocrity. Don''t accept it.', 'founder', 0, 7),
('Build', 'Tony Fadell', 'He built the iPod. He knows how to make things people love. It''s about the details.', 'founder', 0, 8),
('Trillion Dollar Coach', 'Eric Schmidt', 'The best CEOs have a coach. You can''t see your own swing. Get help.', 'founder', 0, 9),
('Venture Deals', 'Brad Feld', 'Don''t get tricked by the money guys. Understand the term sheet. Protect your equity.', 'founder', 0, 10),
('Secrets of Sand Hill Road', 'Scott Kupor', 'VCs follow patterns. Know what they want before you walk in the room.', 'founder', 0, 11),
('The Innovator''s Dilemma', 'Clayton Christensen', 'Doing everything ''right'' can still kill your company. Disruption is inevitable. Be the disruption.', 'founder', 1, 0),
('Crossing the Chasm', 'Geoffrey Moore', 'Early adopters are easy. The mainstream is hard. This is how you cross that gap.', 'founder', 1, 1),
('Blue Ocean Strategy', 'W. Chan Kim', 'Stop fighting in a crowded pool. Go where nobody else is. Find the open water.', 'founder', 1, 2),
('The Lean Startup', 'Eric Ries', 'Don''t guess. Experiment. Treat your business like a science lab. Fail fast.', 'founder', 1, 3),
('Loonshots', 'Safi Bahcall', 'Crazy ideas change the world. You need a system to protect them from the suits.', 'founder', 1, 4),
('The Goal', 'Eliyahu Goldratt', 'Find the bottleneck. Fix the bottleneck. Everything else is a waste of time.', 'founder', 1, 5),
('Thinking in Systems', 'Donella Meadows', 'The world isn''t a line; it''s a loop. Understand feedback loops or get crushed by them.', 'founder', 1, 6),
('Scale', 'Geoffrey West', 'Companies die. Cities survive. Understand the math of growth and death.', 'founder', 1, 7),
('Complexity: A Guided Tour', 'Melanie Mitchell', 'Chaos has a pattern. Learn how order comes from nothing. It''s beautiful.', 'founder', 1, 8),
('Algorithm Design Manual', 'Steven Skiena', 'Think like a computer. Efficiency matters. Sharpen your logic.', 'founder', 1, 9),
('The Mythical Man-Month', 'Frederick Brooks', 'Adding more people to a late project makes it later. It''s a law of physics. Remember it.', 'founder', 1, 10),
('The Design of Everyday Things', 'Don Norman', 'If you can''t figure it out, it''s bad design. Empathy for the user is everything.', 'founder', 1, 11),
('Poor Charlie''s Almanack', 'Charlie Munger', 'He''s smarter than you. Listen to him. Invert, always invert. Avoid stupidity.', 'founder', 2, 0),
('Seeking Wisdom', 'Peter Bevelin', 'Darwin and Munger in one book. It''s a cheat code for thinking clearly.', 'founder', 2, 1),
('The Sovereign Individual', 'James Dale Davidson', 'They predicted Bitcoin in 1997. Understand where the digital world is actually going.', 'founder', 2, 2),
('The Fountainhead', 'Ayn Rand', 'Do not compromise. Build what you believe in. The mob is usually wrong.', 'founder', 2, 3),
('Atlas Shrugged', 'Ayn Rand', 'Production drives the world. Be a producer, not a looter.', 'founder', 2, 4),
('The Lessons of History', 'Will & Ariel Durant', 'Human nature hasn''t changed in 5,000 years. Read this and stop being surprised.', 'founder', 2, 5),
('The Beginning of Infinity', 'David Deutsch', 'Problems are inevitable. Problems are soluble. We can figure anything out.', 'founder', 2, 6),
('The Fabric of Reality', 'David Deutsch', 'Quantum physics, evolution, computation. It''s all one thing. Expand your mind.', 'founder', 2, 7),
('Rationality', 'Steven Pinker', 'Your brain has bugs. Learn logic. Learn probability. Stop being irrational.', 'founder', 2, 8),
('Enlightenment Now', 'Steven Pinker', 'The world is getting better. Don''t be a pessimist. Look at the data.', 'founder', 2, 9),
('Stubborn Attachments', 'Tyler Cowen', 'Growth solves problems. We have a moral duty to grow the economy. Build faster.', 'founder', 2, 10),
('Things Hidden...', 'René Girard', 'You want things because other people want them. Break the cycle of imitation.', 'founder', 2, 11),
('The Selfish Gene', 'Richard Dawkins', 'You are just a vehicle for your genes. Understand the code that drives you.', 'founder', 3, 0),
('The Red Queen', 'Matt Ridley', 'You have to run just to stay in the same place. Evolution never stops. Keep running.', 'founder', 3, 1),
('The Evolution of Everything', 'Matt Ridley', 'No one is in charge. Order emerges from the bottom up. Trust the process.', 'founder', 3, 2),
('Guns, Germs, and Steel', 'Jared Diamond', 'It''s not about race. It''s about geography. Understand the hand you were dealt.', 'founder', 3, 3),
('Collapse', 'Jared Diamond', 'Societies choose to fail. Don''t make the same mistakes. Adapt or die.', 'founder', 3, 4),
('Sapiens', 'Yuval Noah Harari', 'Money is a story. Nations are stories. We rule the world because we can tell lies.', 'founder', 3, 5),
('Homo Deus', 'Yuval Noah Harari', 'What happens when we solve hunger and war? We chase immortality. Get ready.', 'founder', 3, 6),
('The Vital Question', 'Nick Lane', 'Energy is everything. Life is just chemistry fighting entropy. Understand the energy.', 'founder', 3, 7),
('Who We Are and How We Got Here', 'David Reich', 'We are all mixed. Ancient DNA tells the truth. History is migration.', 'founder', 3, 8),
('Behave', 'Robert Sapolsky', 'It''s not good or evil. It''s biology. It''s hormones. Understand the machine inside you.', 'founder', 3, 9),
('Determined', 'Robert Sapolsky', 'Maybe you don''t have free will. That''s a scary thought. Confront it.', 'founder', 3, 10),
('The Moral Animal', 'Robert Wright', 'Your feelings are just evolutionary tools. Don''t trust them blindly. Analyze them.', 'founder', 3, 11),
('Chip War', 'Chris Miller', 'Chips are the new oil. If you can''t make chips, you don''t matter. This is the bottleneck.', 'founder', 4, 0),
('The Prize', 'Daniel Yergin', 'Energy is power. History is just a fight for energy. Know the history.', 'founder', 4, 1),
('The New Map', 'Daniel Yergin', 'The map is changing. Green energy, fracking, China. Navigate the new world.', 'founder', 4, 2),
('World Order', 'Henry Kissinger', 'Chaos is the default. Order is hard. We are losing the order. Pay attention.', 'founder', 4, 3),
('The World for Sale', 'Javier Blas', 'Traders move the world''s resources. They are invisible. See them.', 'founder', 4, 4),
('Freedom''s Forge', 'Arthur Herman', 'Business won WWII. Production capacity is the ultimate deterrent. Build factories.', 'founder', 4, 5),
('Skunk Works', 'Ben Rich', 'They built jets in secret. Small teams, high secrecy, impossible goals. That''s how you innovate.', 'founder', 4, 6),
('The Master Switch', 'Tim Wu', 'Every open system eventually closes. The internet is closing. Fight for it.', 'founder', 4, 7),
('Super Pumped', 'Mike Isaac', 'Uber broke every rule. It was ugly. It worked. Then it broke. Learn from it.', 'founder', 4, 8),
('Amazon Unbound', 'Brad Stone', 'Bezos is ruthless. He is visionary. He is relentless. Study the best.', 'founder', 4, 9),
('The Everything Store', 'Brad Stone', 'Start small. Dream huge. Grind every single day. That is the Amazon way.', 'founder', 4, 10),
('Elon Musk', 'Walter Isaacson', 'He is crazy. He is brilliant. He changes reality. Genius is not neat and tidy.', 'founder', 4, 11),
('The Goldfinch', 'Donna Tartt', 'Art survives. People die. This book hurts, and that''s the point. Feel the loss.', 'academic', 0, 0),
('The Little Friend', 'Donna Tartt', 'Childhood isn''t innocent. It''s terrifying. Look into the dark.', 'academic', 0, 1),
('The Magus', 'John Fowles', 'They are playing a game with your mind. You won''t know what''s real. Let it happen.', 'academic', 0, 2),
('The Collector', 'John Fowles', 'He loves her, so he caged her. It''s disturbing. It''s brilliant. Don''t look away.', 'academic', 0, 3),
('The Sea, The Sea', 'Iris Murdoch', 'We are all vain. We rewrite our own pasts. Watch a man drown in his own ego.', 'academic', 0, 4),
('Atonement', 'Ian McEwan', 'One lie destroys everything. You can''t fix the past. You just have to live with it.', 'academic', 0, 5),
('The Blind Assassin', 'Margaret Atwood', 'Stories inside stories. Betrayal runs deep. History is just what we choose to remember.', 'academic', 0, 6),
('Possession', 'A.S. Byatt', 'Digging up the past is dangerous. Romance is a ghost story. Fall in love with the dead.', 'academic', 0, 7),
('Brideshead Revisited', 'Evelyn Waugh', 'The world is moving on. Beauty is fading. Hold onto it while you can.', 'academic', 0, 8),
('Vile Bodies', 'Evelyn Waugh', 'Partying while the world burns. It''s funny until it''s tragic. Sound familiar?', 'academic', 0, 9),
('The Line of Beauty', 'Alan Hollinghurst', 'It''s seductive. It''s superficial. It cuts deep. Welcome to the 80s.', 'academic', 0, 10),
('White Noise', 'Don DeLillo', 'We are scared of death. We buy things to forget. It doesn''t work. Confront the fear.', 'academic', 0, 11),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'Faith or reason? Choose. This is the heavyweight championship of the soul.', 'academic', 1, 0),
('Demons', 'Fyodor Dostoevsky', 'Ideas have consequences. Radical ideas kill. See what happens when society loses its mind.', 'academic', 1, 1),
('The Idiot', 'Fyodor Dostoevsky', 'Be truly good, and the world will break you. It''s tragic. Be good anyway.', 'academic', 1, 2),
('Notes from Underground', 'Fyodor Dostoevsky', 'He is spiteful. He is sick. He is you. Look in the mirror.', 'academic', 1, 3),
('Anna Karenina', 'Leo Tolstoy', 'Passion burns. Society judges. The train is coming. It''s perfect.', 'academic', 1, 4),
('The Death of Ivan Ilyich', 'Leo Tolstoy', 'You are going to die. Stop living a fake life. Wake up before it''s too late.', 'academic', 1, 5),
('Fathers and Sons', 'Ivan Turgenev', 'The old vs. the new. Nihilism vs. tradition. The fight never ends.', 'academic', 1, 6),
('The Stranger', 'Albert Camus', 'He refused to lie. He refused to fake emotion. Society hated him for it. Be real.', 'academic', 1, 7),
('The Plague', 'Albert Camus', 'The world is sick. There is no cure. Do your job anyway. That is dignity.', 'academic', 1, 8),
('The Myth of Sisyphus', 'Albert Camus', 'Life is absurd. Push the rock up the hill. Smile while you do it.', 'academic', 1, 9),
('Nausea', 'Jean-Paul Sartre', 'Existence is sticky. It''s overwhelming. Feel the weight of just being alive.', 'academic', 1, 10),
('No Exit', 'Jean-Paul Sartre', 'There is no escape. Hell is other people. Deal with them.', 'academic', 1, 11),
('The Sailor Who Fell from Grace...', 'Yukio Mishima', 'Glory is dangerous. Domesticity is boring. He chose glory. Watch the fall.', 'academic', 2, 0),
('Spring Snow', 'Yukio Mishima', 'Beauty is fragile. It breaks easily. Watch it shatter.', 'academic', 2, 1),
('The Temple of the Golden Pavilion', 'Yukio Mishima', 'It was too beautiful. He had to burn it. Obsession destroys.', 'academic', 2, 2),
('Runaway Horses', 'Yukio Mishima', 'Purity leads to blood. He wanted to change the world. He died for it.', 'academic', 2, 3),
('No Longer Human', 'Osamu Dazai', 'He wore a mask his whole life. He was terrified of humans. It''s heartbreaking.', 'academic', 2, 4),
('The Setting Sun', 'Osamu Dazai', 'The old world is dying. The aristocracy is fading. There is beauty in the decline.', 'academic', 2, 5),
('Norwegian Wood', 'Haruki Murakami', 'Growing up hurts. People leave. You have to keep walking. Listen to the music.', 'academic', 2, 6),
('Kafka on the Shore', 'Haruki Murakami', 'Cats talk. Fish fall from the sky. Your subconscious is wild. Go explore it.', 'academic', 2, 7),
('The Wind-Up Bird Chronicle', 'Haruki Murakami', 'Go down into the well. Face your darkness. Find what''s missing.', 'academic', 2, 8),
('Kitchen', 'Banana Yoshimoto', 'Death happens. Eat good food. Keep living. It''s simple and profound.', 'academic', 2, 9),
('Snow Country', 'Yasunari Kawabata', 'It''s cold. It''s lonely. It''s wasted love. It''s stunningly beautiful.', 'academic', 2, 10),
('Thousand Cranes', 'Yasunari Kawabata', 'The tea ceremony hides guilt. The past stains the present. Drink the tea.', 'academic', 2, 11),
('De Profundis', 'Oscar Wilde', 'He lost everything. He found his soul in prison. Suffering teaches you who you are.', 'academic', 3, 0),
('The Importance of Being Earnest', 'Oscar Wilde', 'Life is too important to be taken seriously. Laugh at everything.', 'academic', 3, 1),
('Against Nature', 'J.K. Huysmans', 'He hated nature. He loved artificiality. This is the book that corrupted Dorian Gray.', 'academic', 3, 2),
('Lolita', 'Vladimir Nabokov', 'The prose is beautiful. The subject is a monster. Can you separate them?', 'academic', 3, 3),
('Pale Fire', 'Vladimir Nabokov', 'It''s a puzzle. It''s a game. The narrator is lying to you. Can you solve it?', 'academic', 3, 4),
('Pnin', 'Vladimir Nabokov', 'He is awkward. He is exiled. He is tragic. You will love him.', 'academic', 3, 5),
('The Master and Margarita', 'Mikhail Bulgakov', 'The Devil came to Moscow. He caused chaos. It''s hilarious. Magic is real.', 'academic', 3, 6),
('Perfume', 'Patrick Süskind', 'He had no scent, so he stole yours. It''s dark. It smells incredible.', 'academic', 3, 7),
('American Psycho', 'Bret Easton Ellis', 'Suits. Cards. Murders. It''s empty. It''s the 80s. Look at the void.', 'academic', 3, 8),
('Less Than Zero', 'Bret Easton Ellis', 'They are young, rich, and dead inside. The sun is shining. Nothing matters.', 'academic', 3, 9),
('The Unbearable Lightness of Being', 'Milan Kundera', 'Heavy or light? Which do you choose? Every choice disappears once you make it.', 'academic', 3, 10),
('The Book of Laughter and Forgetting', 'Milan Kundera', 'They want to erase history. Don''t let them. Memory is resistance.', 'academic', 3, 11),
('Stoner', 'John Williams', 'He lived a quiet life. He died. It was beautiful. This book will change you.', 'academic', 4, 0),
('Augustus', 'John Williams', 'He ruled the world. He lost his daughter. Power is lonely. Read the letters.', 'academic', 4, 1),
('Butcher''s Crossing', 'John Williams', 'The West wasn''t heroic. It was brutal. Nature doesn''t care about your dreams.', 'academic', 4, 2),
('Revolutionary Road', 'Richard Yates', 'The suburbs are a trap. The dream is a lie. They scream in the kitchen. Listen.', 'academic', 4, 3),
('The Heart is a Lonely Hunter', 'Carson McCullers', 'Everyone is lonely. Everyone wants to be heard. Listen to the silence.', 'academic', 4, 4),
('A Room of One''s Own', 'Virginia Woolf', 'You need money and a room to create. It''s practical. Get the money.', 'academic', 4, 5),
('Mrs. Dalloway', 'Virginia Woolf', 'One day holds a whole life. The flowers. The party. The suicide. It''s all connected.', 'academic', 4, 6),
('To the Lighthouse', 'Virginia Woolf', 'Time passes. People die. The house decays. Art remains.', 'academic', 4, 7),
('The Bell Jar', 'Sylvia Plath', 'She was talented. She was sinking. The bell jar trapped her. Breathe fresh air.', 'academic', 4, 8),
('Play It As It Lays', 'Joan Didion', 'California is empty. The snake is in the garden. Keep driving on the freeway.', 'academic', 4, 9),
('The Year of Magical Thinking', 'Joan Didion', 'Grief makes you crazy. You think you can bring them back. You can''t. Read this.', 'academic', 4, 10),
('My Year of Rest and Relaxation', 'Ottessa Moshfegh', 'She slept for a year. She hated everything. It''s dark. It funny. Wake up.', 'academic', 4, 11),
('The Three-Body Problem', 'Cixin Liu', 'Physics is a weapon. The universe is a forest. Hunters are hiding. Be quiet.', 'futurist', 0, 0),
('The Dark Forest', 'Cixin Liu', 'If they find us, they destroy us. This is the Fermi Paradox solved. It''s terrifying.', 'futurist', 0, 1),
('Death''s End', 'Cixin Liu', 'Dimensions collapse. The universe dies. Think bigger. Bigger than that.', 'futurist', 0, 2),
('Project Hail Mary', 'Andy Weir', 'The sun is dying. One guy has to fix it. Science is the superpower. Use it.', 'futurist', 0, 3),
('The Martian', 'Andy Weir', 'He''s stuck on Mars. He doesn''t panic. He does the math. Do the math.', 'futurist', 0, 4),
('Contact', 'Carl Sagan', 'It''s not about the aliens. It''s about us. Are we ready? Probably not.', 'futurist', 0, 5),
('Rendezvous with Rama', 'Arthur C. Clarke', 'A cylinder enters the system. It ignores us. We are ants. Accept it.', 'futurist', 0, 6),
('Childhood''s End', 'Arthur C. Clarke', 'The aliens bring peace. It costs us our humanity. Is it worth it?', 'futurist', 0, 7),
('Solaris', 'Stanislaw Lem', 'The planet is alive. It reads your mind. You can''t talk to it. It''s truly alien.', 'futurist', 0, 8),
('His Master''s Voice', 'Stanislaw Lem', 'We got a signal. We have no idea what it means. We are too stupid. That''s humbling.', 'futurist', 0, 9),
('Blindsight', 'Peter Watts', 'Consciousness is a glitch. Space vampires are real. This will break your brain.', 'futurist', 0, 10),
('Echopraxia', 'Peter Watts', 'God, biology, and hive minds. Evolution isn''t done with us. Adapt.', 'futurist', 0, 11),
('Neuromancer', 'William Gibson', 'He invented the Matrix before the internet existed. The sky is the color of a TV. Jack in.', 'futurist', 1, 0),
('Count Zero', 'William Gibson', 'Voodoo gods in the code. Corporate extraction teams. The future is dirty. Love it.', 'futurist', 1, 1),
('Mona Lisa Overdrive', 'William Gibson', 'The Sprawl is real. The rich live forever. The street finds its own use for things.', 'futurist', 1, 2),
('Snow Crash', 'Neal Stephenson', 'The Metaverse. Avatars. Pizza delivery mafia. He predicted it all. Read the manual.', 'futurist', 1, 3),
('The Diamond Age', 'Neal Stephenson', '3D printers make everything. Education is the only value left. Learn or die.', 'futurist', 1, 4),
('Cryptonomicon', 'Neal Stephenson', 'Codes. Gold. Data havens. The roots of crypto are here. Decode it.', 'futurist', 1, 5),
('Seveneves', 'Neal Stephenson', 'The moon blew up. We have two years. Science has to save us. Get to work.', 'futurist', 1, 6),
('Altered Carbon', 'Richard K. Morgan', 'Death is obsolete. You are just software. Sleeves are cheap. Identity is fluid.', 'futurist', 1, 7),
('Do Androids Dream of Electric Sheep?', 'Philip K. Dick', 'What is real? What is fake? Does it matter if you feel love? Ask the robot.', 'futurist', 1, 8),
('Ubik', 'Philip K. Dick', 'Time is decaying. Reality is eating itself. Buy Ubik. It saves you.', 'futurist', 1, 9),
('A Scanner Darkly', 'Philip K. Dick', 'Drugs destroy your mind. The surveillance state watches. You lose yourself. Watch out.', 'futurist', 1, 10),
('Ready Player One', 'Ernest Cline', 'The real world sucks. We hide in the game. It''s a warning, not a manual.', 'futurist', 1, 11),
('Dune', 'Frank Herbert', 'The spice must flow. Politics, religion, ecology. It''s all one system. Control the resource.', 'futurist', 2, 0),
('Dune Messiah', 'Frank Herbert', 'Heroes are dangerous. Jihad kills billions. Be careful who you follow.', 'futurist', 2, 1),
('Children of Dune', 'Frank Herbert', 'Change is painful. To save humanity, you have to become a monster.', 'futurist', 2, 2),
('God Emperor of Dune', 'Frank Herbert', 'He lived 3,000 years. He is a worm. He sees the Golden Path. Trust the long game.', 'futurist', 2, 3),
('Foundation', 'Isaac Asimov', 'Empires fall. Math predicts it. We can shorten the dark age. Build the Foundation.', 'futurist', 2, 4),
('Foundation and Empire', 'Isaac Asimov', 'The plan was perfect. Then a mutant showed up. Outliers break models. Prepare for them.', 'futurist', 2, 5),
('Second Foundation', 'Isaac Asimov', 'Mind control vs. physics. Who runs the galaxy? The smartest guys in the room.', 'futurist', 2, 6),
('Hyperion', 'Dan Simmons', 'The Shrike is coming. Time is leaking. Tell your story before you die.', 'futurist', 2, 7),
('The Fall of Hyperion', 'Dan Simmons', 'The AI Core is manipulating us. We are parasites. War is coming. Choose a side.', 'futurist', 2, 8),
('Endymion', 'Dan Simmons', 'Love moves the universe. Evolution takes a leap. The adventure never ends.', 'futurist', 2, 9),
('Consider Phlebas', 'Iain M. Banks', 'The Culture has everything. They fight for fun. Utopia is weird. See it.', 'futurist', 2, 10),
('The Player of Games', 'Iain M. Banks', 'They play games to decide empires. Strategy is everything. Play better.', 'futurist', 2, 11),
('Superintelligence', 'Nick Bostrom', 'AI will be smarter than us. If we don''t align it, we die. This is the most important problem.', 'futurist', 3, 0),
('Life 3.0', 'Max Tegmark', 'We are designing our successors. Hardware. Software. Life. Choose the future.', 'futurist', 3, 1),
('Human Compatible', 'Stuart Russell', 'Robots need to doubt. Uncertainty is safety. Teach them to ask questions.', 'futurist', 3, 2),
('The Singularity is Near', 'Ray Kurzweil', 'Exponential growth is crazy. We will merge with machines. Live long enough to see it.', 'futurist', 3, 3),
('Nexus', 'Yuval Noah Harari', 'Information networks run history. AI is a new network. It can hack us. Wake up.', 'futurist', 3, 4),
('The Coming Wave', 'Mustafa Suleyman', 'Tech is getting cheaper and deadlier. Containment is hard. We have to try.', 'futurist', 3, 5),
('Permutation City', 'Greg Egan', 'Copy your brain. Run it on a server. Are you still you? The math says yes.', 'futurist', 3, 6),
('Diaspora', 'Greg Egan', 'Flesh is weak. Become software. Explore the stars. Leave the body behind.', 'futurist', 3, 7),
('Axiomatic', 'Greg Egan', 'Can you edit your beliefs? Can you hack your own love? Bio-hacking is the future.', 'futurist', 3, 8),
('Exhalation', 'Ted Chiang', 'The universe is breathing out. Entropy wins. Build beauty while you can.', 'futurist', 3, 9),
('Stories of Your Life and Others', 'Ted Chiang', 'Language changes how you think. See time all at once. Communicate better.', 'futurist', 3, 10),
('I, Robot', 'Isaac Asimov', 'Three laws. Logic puzzles. Robots try to help, but logic is tricky. Debug the code.', 'futurist', 3, 11),
('The Ministry for the Future', 'Kim Stanley Robinson', 'Heat waves kill. Carbon coin saves us. It''s a blueprint. We can actually fix this.', 'futurist', 4, 0),
('Red Mars', 'Kim Stanley Robinson', 'Build a world from scratch. Politics, engineering, botany. Mars is the next frontier.', 'futurist', 4, 1),
('Green Mars', 'Kim Stanley Robinson', 'Terraforming takes time. Revolution happens fast. Freedom on a new planet.', 'futurist', 4, 2),
('Blue Mars', 'Kim Stanley Robinson', 'Live forever. Adapt to space. Humanity evolves. The journey is long.', 'futurist', 4, 3),
('Aurora', 'Kim Stanley Robinson', 'Starships are hard. Biology fights back. Maybe Earth is the only home. Protect it.', 'futurist', 4, 4),
('Parable of the Sower', 'Octavia Butler', 'Society crumbles. Fire spreads. God is Change. Build a community to survive.', 'futurist', 4, 5),
('Parable of the Talents', 'Octavia Butler', 'Fanatics take over. They want the old ways. Fight for the new way.', 'futurist', 4, 6),
('Oryx and Crake', 'Margaret Atwood', 'Science without ethics is suicide. We engineered our replacement. Oops.', 'futurist', 4, 7),
('The Year of the Flood', 'Margaret Atwood', 'The waterless flood. The gardeners survive. Eat your veggies. survive the plague.', 'futurist', 4, 8),
('MaddAddam', 'Margaret Atwood', 'New myths for a new world. We have to live with the monsters we made.', 'futurist', 4, 9),
('Station Eleven', 'Emily St. John Mandel', 'Survival is insufficient. We need art. We need Shakespeare. Even at the end of the world.', 'futurist', 4, 10),
('A Canticle for Leibowitz', 'Walter M. Miller Jr.', 'We blew it up. Monks save the books. We learn it again. We blow it up again. Break the cycle.', 'futurist', 4, 11),
('The 48 Laws of Power', 'Robert Greene', 'People are playing games. You are losing because you don''t know the rules. Learn the rules.', 'alchemist', 0, 0),
('The Laws of Human Nature', 'Robert Greene', 'You have a dark side. Everyone does. Stop being naive. See the shadow.', 'alchemist', 0, 1),
('The Art of Seduction', 'Robert Greene', 'Charm is a weapon. Use it. Make them fall in love with you.', 'alchemist', 0, 2),
('The 33 Strategies of War', 'Robert Greene', 'Life is conflict. Don''t fight fair. Fight to win. Strategy over brute force.', 'alchemist', 0, 3),
('Mastery', 'Robert Greene', 'There are no shortcuts. 10,000 hours. Deep focus. Be undeniable.', 'alchemist', 0, 4),
('The Prince', 'Niccolò Machiavelli', 'It''s better to be feared than loved. It''s ugly, but it''s true. Face reality.', 'alchemist', 0, 5),
('Discourses on Livy', 'Niccolò Machiavelli', 'Republics fall when people get lazy. Virtue requires vigilance. Wake up.', 'alchemist', 0, 6),
('The Art of War', 'Sun Tzu', 'The best victory is the one without fighting. Know yourself. Know your enemy.', 'alchemist', 0, 7),
('The Book of Five Rings', 'Miyamoto Musashi', 'There is only one way: the way of the warrior. Discipline. Focus. Cut.', 'alchemist', 0, 8),
('Meditations', 'Marcus Aurelius', 'The emperor of the world was sad. He stayed strong. Control your mind. It''s all you have.', 'alchemist', 0, 9),
('Letters from a Stoic', 'Seneca', 'Time is short. You are wasting it. Stop complaining. Start living.', 'alchemist', 0, 10),
('Maxims', 'La Rochefoucauld', 'We are all vain. We act from self-interest. Don''t get mad. Just observe.', 'alchemist', 0, 11),
('Never Split the Difference', 'Chris Voss', 'Hostages are on the line. Splitting the difference kills them. Get what you want.', 'alchemist', 1, 0),
('Influence', 'Robert Cialdini', 'Six buttons control human brains. Reciprocity. Scarcity. Push the buttons.', 'alchemist', 1, 1),
('Pre-Suasion', 'Robert Cialdini', 'The battle is won before it starts. Set the stage. Frame the argument.', 'alchemist', 1, 2),
('Start with No', 'Jim Camp', 'Yes is fake. No is real. Make them say no. Then you can talk.', 'alchemist', 1, 3),
('Getting to Yes', 'Roger Fisher', 'Don''t attack the person. Attack the problem. Find the win-win. Build the bridge.', 'alchemist', 1, 4),
('Crucial Conversations', 'Kerry Patterson', 'High stakes. High emotion. Don''t freeze. Don''t explode. Talk it out.', 'alchemist', 1, 5),
('Pitch Anything', 'Oren Klaff', 'The croc brain is in charge. Frame the deal. Be the prize. Don''t chase.', 'alchemist', 1, 6),
('Flip the Script', 'Oren Klaff', 'Inception is real. Make them think it was their idea. That''s true persuasion.', 'alchemist', 1, 7),
('Made to Stick', 'Chip Heath', 'Why do urban legends survive? They are sticky. Make your ideas sticky.', 'alchemist', 1, 8),
('Switch', 'Chip Heath', 'The elephant is emotional. The rider is rational. Direct the rider. Motivate the elephant.', 'alchemist', 1, 9),
('To Sell Is Human', 'Daniel Pink', 'We are all selling. Teachers, doctors, parents. Learn to move people. It''s noble.', 'alchemist', 1, 10),
('Win Bigly', 'Scott Adams', 'Facts don''t matter. Persuasion matters. Master the filter. Control the reality.', 'alchemist', 1, 11),
('The Status Game', 'Will Storr', 'You want status. It drives everything. Admit it. Then you can play the game.', 'alchemist', 2, 0),
('The Science of Storytelling', 'Will Storr', 'Your brain hallucinates reality. Stories control the hallucination. Tell better stories.', 'alchemist', 2, 1),
('Selfie', 'Will Storr', 'We are obsessed with ourselves. It''s making us sick. Look outward. Get over yourself.', 'alchemist', 2, 2),
('Games People Play', 'Eric Berne', 'You are running a script. ''Poor me.'' ''Yes, but.'' Stop playing the game.', 'alchemist', 2, 3),
('What Do You Say After...', 'Eric Berne', 'Your destiny was written when you were six. Rewrite the script. Take control.', 'alchemist', 2, 4),
('I''m OK – You''re OK', 'Thomas A. Harris', 'You feel like a child. You act like a parent. Be an adult. It''s hard.', 'alchemist', 2, 5),
('Predictably Irrational', 'Dan Ariely', 'You think you are logical. You aren''t. You are weird. Understand your bugs.', 'alchemist', 2, 6),
('The Righteous Mind', 'Jonathan Haidt', 'Politics is religion. They aren''t evil; they just have different morals. Understand them.', 'alchemist', 2, 7),
('The Coddling of American Mind', 'Jonathan Haidt', 'Safetyism makes you weak. Trauma makes you strong. Stop hiding.', 'alchemist', 2, 8),
('Thinking, Fast and Slow', 'Daniel Kahneman', 'System 1 is fast and stupid. System 2 is slow and lazy. Wake up System 2.', 'alchemist', 2, 9),
('Noise', 'Daniel Kahneman', 'Your judgment is random. You are inconsistent. Clean up the noise.', 'alchemist', 2, 10),
('Nudge', 'Richard Thaler', 'People are lazy. Design the default choice. Help them do the right thing.', 'alchemist', 2, 11),
('Trust Me, I''m Lying', 'Ryan Holiday', 'Blogs lie. News lies. It''s all a hustle. Don''t believe the clickbait.', 'alchemist', 3, 0),
('Conspiracy', 'Ryan Holiday', 'Thiel plotted for years. He destroyed Gawker. Patience and money win. Be careful.', 'alchemist', 3, 1),
('Ego Is the Enemy', 'Ryan Holiday', 'Success goes to your head. Failure breaks your heart. Ego is the enemy. Kill it.', 'alchemist', 3, 2),
('Propaganda', 'Edward Bernays', 'He made women smoke. He made you eat bacon. He engineered consent. Know the tricks.', 'alchemist', 3, 3),
('Manufacturing Consent', 'Noam Chomsky', 'The media sells audiences to advertisers. You are the product. Wake up.', 'alchemist', 3, 4),
('Amusing Ourselves to Death', 'Neil Postman', 'Orwell was wrong. Huxley was right. We love our oppression. Turn off the TV.', 'alchemist', 3, 5),
('The Image', 'Daniel Boorstin', 'We prefer the fake to the real. Celebrities are famous for being famous. It''s hollow.', 'alchemist', 3, 6),
('Crowds and Power', 'Elias Canetti', 'The mob wants to grow. The mob wants to destroy. Don''t get lost in the crowd.', 'alchemist', 3, 7),
('The True Believer', 'Eric Hoffer', 'Fanatics are lonely. They want to belong. They will burn the world to feel safe.', 'alchemist', 3, 8),
('So You''ve Been Publicly Shamed', 'Jon Ronson', 'One tweet can ruin your life. The internet is a mob. Watch what you say.', 'alchemist', 3, 9),
('The Psychopath Test', 'Jon Ronson', 'CEOs are psychopaths. Leaders are crazy. Maybe you are too. Take the test.', 'alchemist', 3, 10),
('Mistakes Were Made', 'Carol Tavris', 'You never admit you''re wrong. You justify it. Stop justifying. Admit it.', 'alchemist', 3, 11),
('Midnight in the Garden...', 'John Berendt', 'Savannah is weird. Money hides secrets. A murder exposes it all. Atmosphere is power.', 'alchemist', 4, 0),
('The Devil in the White City', 'Erik Larson', 'He built a murder castle. He was charming. Evil wears a nice suit.', 'alchemist', 4, 1),
('In the Garden of Beasts', 'Erik Larson', 'They danced while the Nazis rose. Denial is comfortable. Look at the monster.', 'alchemist', 4, 2),
('Catch Me If You Can', 'Frank Abagnale', 'He was a pilot. A doctor. A lawyer. He was a kid. Confidence is the only currency.', 'alchemist', 4, 3),
('The Wolf of Wall Street', 'Jordan Belfort', 'Sell me this pen. Greed is a drug. He had it all and lost it. Don''t be him.', 'alchemist', 4, 4),
('Billion Dollar Whale', 'Tom Wright', 'He stole billions. He partied with Leo. No one checked the books. Audit everything.', 'alchemist', 4, 5),
('Cultish', 'Amanda Montell', 'SoulCycle is a cult. Startups are cults. Language controls you. Speak clearly.', 'alchemist', 4, 6),
('Going Clear', 'Lawrence Wright', 'Belief is powerful. Belief is dangerous. They trapped Tom Cruise. Don''t get trapped.', 'alchemist', 4, 7),
('Under the Banner of Heaven', 'Jon Krakauer', 'God told them to kill. Fundamentalism is scary. Faith needs reason.', 'alchemist', 4, 8),
('Helter Skelter', 'Vincent Bugliosi', 'Manson controlled them. He didn''t kill anyone. He made them do it. Influence is deadly.', 'alchemist', 4, 9),
('The Adversary', 'Emmanuel Carrère', 'He lied for 20 years. He killed his family to keep the lie. The truth sets you free.', 'alchemist', 4, 10),
('In Cold Blood', 'Truman Capote', 'Two drifters killed a family. It was pointless. It changed writing forever. Read the master.', 'alchemist', 4, 11)
ON CONFLICT (title, author, persona_id, module_index) 
DO UPDATE SET 
  why = EXCLUDED.why,
  order_index = EXCLUDED.order_index,
  updated_at = now();
